jobs:
  include:
    - stage: backend
      language: node_js
      node_js:
        - "stable"

      services:
        - "mongodb"
        - "docker"

      before_script:
        - sleep 15
        - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - docker-compose up --build -d

      script:
        - cd labellab-server/
        - rm package-lock.json
        - npm install && npm test

      after_script:
        - docker-compose down
    - stage: frontend
      language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      before_script: cd labellab-client
      script:
        - npm install
        - npm test
        - npm run build
